(() => {
  "use strict";
  const PATHS = { real: "../outputs/demo_traces/sims-real-0.60.json", zero: "../outputs/demo_traces/sims-zero-0.60.json", bookmarks: "../outputs/demo_traces/sims-0.60-bookmarks.json" };
  const FEATURES = ["source_buffer_token_count", "source_buffer_character_count", "source_clock_elapsed_ms", "current_target_token_count", "previous_target_token_count", "target_token_count_delta", "previous_current_lcp_ratio", "previous_current_change_ratio", "prior_committed_unit_count", "previous_committed_source_tokens", "previous_committed_target_tokens"];
  const MAX_PLAYBACK_DELAY_MS = 1500;
  const $ = (selector) => document.querySelector(selector);
  const state = { real: null, zero: null, bookmarks: null, index: 0, speed: 1, timer: null, presentation: false, pauseOnDivergence: false };

  function formatClock(milliseconds, decimals = true) { const seconds = milliseconds / 1000; if (!decimals) return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`; const minutes = Math.floor(seconds / 60); return `${String(minutes).padStart(2, "0")}:${(seconds % 60).toFixed(3).padStart(6, "0")}`; }
  function escapeHtml(value) { return String(value ?? "").replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]); }
  function probability(value) { return value == null ? "-" : value.toFixed(6); }
  function range(event) { return `${event.candidate_source_start}-${event.candidate_source_end}`; }
  function tokenCount(event) { return event.candidate_source_end - event.candidate_source_start + 1; }
  function isSameSpan(real, zero) { return real.candidate_source_start === zero.candidate_source_start && real.candidate_source_end === zero.candidate_source_end; }
  function commitsUntil(events) { return events.slice(0, state.index + 1).filter((event) => event.decision === "COMMIT"); }
  function decisionIcon(decision) { return ({ WAIT: "...", LISTEN: "||", COMMIT: "+" })[decision]; }
  function sourceTokens(event) { return event.candidate_source_text.trim().split(/\s+/); }
  function incomingToken(event) { return sourceTokens(event).at(-1); }

  function fail(message) { $("#error-panel").hidden = false; $("#error-panel").textContent = `Research-data error\n\n${message}\n\nPlayback has not started. Check that the pre-generated DEV trace artifacts are present and synchronized.`; $("#app").hidden = true; }
  async function fetchJson(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`); return response.json(); }
  function validateEvent(event, position, label) { if (!event || event.event_index !== position || event.source_token_end !== position || typeof event.observation_ms !== "number") throw new Error(`${label} has an invalid event at index ${position}.`); if (!Number.isInteger(event.candidate_source_start) || !Number.isInteger(event.candidate_source_end) || event.candidate_source_start > event.candidate_source_end || event.candidate_source_end !== position) throw new Error(`${label} has an invalid candidate source span at event ${position}.`); if (sourceTokens(event).length !== tokenCount(event)) throw new Error(`${label} candidate source text does not match its span at event ${position}.`); if (!["WAIT", "LISTEN", "COMMIT"].includes(event.decision)) throw new Error(`${label} has an invalid decision at event ${position}.`); if (event.decision === "WAIT" && (event.p_commit !== null || event.candidate_translation !== null || event.numeric_features !== null)) throw new Error(`${label} WAIT event ${position} contains unavailable inference values.`); if (event.decision !== "WAIT" && (typeof event.p_commit !== "number" || typeof event.candidate_translation !== "string")) throw new Error(`${label} ${event.decision} event ${position} is missing policy data.`); }
  function validate(real, zero, bookmarkFile) { const keys = ["artifact_version", "talk_id", "split", "threshold", "checkpoint_sha256", "source_token_count", "source_final_emit_ms"]; for (const key of keys) if (real[key] !== zero[key]) throw new Error(`Trace metadata mismatch for ${key}.`); if (real.prepared_context_mode !== "real" || zero.prepared_context_mode !== "zero") throw new Error("Trace prepared-context modes must be real and zero."); if (!Array.isArray(real.events) || !Array.isArray(zero.events) || real.events.length !== zero.events.length || real.events.length !== real.source_token_count) throw new Error("Trace event count mismatch."); for (let index = 0; index < real.events.length; index += 1) { validateEvent(real.events[index], index, "REAL"); validateEvent(zero.events[index], index, "ZERO"); for (const key of ["event_index", "source_token_end", "observation_ms"]) if (real.events[index][key] !== zero.events[index][key]) throw new Error(`Source timeline mismatch at event ${index} for ${key}.`); if (incomingToken(real.events[index]) !== incomingToken(zero.events[index])) throw new Error(`Source token mismatch at event ${index}.`); } if (bookmarkFile.talk_id !== real.talk_id || bookmarkFile.threshold !== real.threshold || !Array.isArray(bookmarkFile.bookmarks)) throw new Error("Bookmark metadata does not match the trace pair."); for (const bookmark of bookmarkFile.bookmarks) { const event = real.events[bookmark.event_index]; if (!event || event.observation_ms !== bookmark.observation_ms) throw new Error(`Bookmark ${bookmark.id || "(unnamed)"} does not reference a valid synchronized event.`); } const first = bookmarkFile.bookmarks.find((bookmark) => bookmark.id === "first-divergence"); if (!first) throw new Error("Required first-divergence bookmark is missing."); return first.event_index; }
  function chips(event) { return sourceTokens(event).map((token, index, tokens) => `<span class="source-chip ${index === tokens.length - 1 ? "newest" : ""}">${escapeHtml(token)}</span>`).join(""); }
  function card(mode, event) { const unavailable = event.decision === "WAIT"; const forced = event.is_forced ? `<span class="forced">Forced: ${escapeHtml(event.decision_reason)}</span>` : ""; const bar = unavailable ? "" : `<div class="prob-track" aria-label="p COMMIT ${probability(event.p_commit)}; threshold ${event.threshold.toFixed(2)}"><span class="prob-fill" style="width:${event.p_commit * 100}%"></span><span class="threshold-marker" style="left:${event.threshold * 100}%"></span></div><div class="threshold-caption"><span>0.0</span><span>threshold = ${event.threshold.toFixed(2)}</span><span>1.0</span></div>`; const status = unavailable ? "<p class=\"wait-explanation\">Need at least 4 buffered source tokens before translator/policy inference.</p>" : event.decision === "LISTEN" ? "<p class=\"listen-explanation\">The current source remains uncommitted and will continue accumulating.</p>" : "<p class=\"commit-explanation\">This source span becomes committed.</p>"; return `<div class="card-header"><div><p class="mode">${mode} CONTEXT</p><span class="mode-detail">prepared_context_mode = ${mode.toLowerCase()}</span></div><span class="decision ${event.decision.toLowerCase()}"><span class="decision-symbol" aria-hidden="true">${decisionIcon(event.decision)}</span>${event.decision}</span></div><div class="field uncommitted-source"><span class="field-label">Current uncommitted source</span><p class="field-value span-meta">span ${range(event)} &middot; ${tokenCount(event)} ${tokenCount(event) === 1 ? "token" : "tokens"}</p><div class="source-chips" aria-label="Current uncommitted source tokens">${chips(event)}</div></div><div class="field"><span class="field-label">Candidate translation</span><p class="field-value translation">${unavailable ? "Not evaluated" : escapeHtml(event.candidate_translation)}</p></div><div class="field"><span class="field-label">p(COMMIT)</span><div class="probability"><strong>${unavailable ? "-" : probability(event.p_commit)}</strong><span>${unavailable ? "Not evaluated" : "p(COMMIT)"}</span></div>${bar}</div><div class="field"><span class="field-label">Decision reason</span><p class="field-value">${escapeHtml(event.decision_reason)} ${forced}</p></div>${status}`; }
  function renderSource(real, zero) { const start = Math.max(0, state.index - 45); const tokens = []; for (let index = start; index <= state.index; index += 1) { const token = incomingToken(state.real.events[index]); const klass = index === state.index ? "newest" : index >= state.index - 12 ? "recent" : ""; tokens.push(`<span class="source-token ${klass}">${escapeHtml(token)}</span>`); } $("#incoming-token").innerHTML = `<p class="field-label">Incoming source token</p><strong class="incoming-word">&ldquo;${escapeHtml(incomingToken(real))}&rdquo;</strong><p class="incoming-meta">source clock: ${formatClock(real.observation_ms)}<br>token ${real.source_token_end} / ${state.real.events.length - 1}</p>`; $("#source-stream").innerHTML = tokens.join(" "); $("#source-observation").textContent = `event ${real.event_index} / ${state.real.events.length - 1} at ${formatClock(real.observation_ms)}`; $("#candidate-ranges").textContent = isSameSpan(real, zero) ? `same: ${range(real)}` : `REAL ${range(real)} | ZERO ${range(zero)}`; }
  function renderKnowledge() { const context = state.real.prepared_context; $("#knowledge-content").innerHTML = `<p class="knowledge-lead">Prepared source exists in BOTH conditions.</p><div class="norm-grid"><div class="norm real"><span class="eyebrow">REAL effective norm</span><strong>${state.real.prepared_context.prepared_context_effective_embedding_norm.toFixed(1)}</strong></div><div class="norm zero"><span class="eyebrow">ZERO effective norm</span><strong>${state.zero.prepared_context.prepared_context_effective_embedding_norm.toFixed(1)}</strong></div></div><table class="knowledge-table"><tr><th>Eligible source</th><td>${escapeHtml((context.eligible_source_ids || []).join(", "))}</td></tr><tr><th>Eligibility</th><td>SAFE_PRETALK_CONFIRMED</td></tr><tr><th>Representation</th><td>${escapeHtml(context.representation_version)}</td></tr><tr><th>Source count</th><td>${context.source_count}</td></tr><tr><th>Embedding dimension</th><td>${context.embedding_dimension}</td></tr></table><p class="knowledge-note"><strong>ZERO disables only the policy embedding.</strong><br>EnViT5 receives the same source-only input design. ZERO does not remove provenance or prepared-document availability.</p>`; }
  function renderTimeline() { const finalMs = state.real.source_final_emit_ms; const marker = (event, kind) => `<i class="marker ${kind}" style="left:${(event.observation_ms / finalMs) * 100}%" title="${kind.toUpperCase()} commit at ${formatClock(event.observation_ms)}"></i>`; const realCommits = commitsUntil(state.real.events); const zeroCommits = commitsUntil(state.zero.events); $("#commit-timeline").innerHTML = `<div class="timeline-scale"><span>00:00</span><span>${formatClock(finalMs, false)}</span></div><span class="timeline-row-label real">REAL</span><span class="timeline-row-label zero">ZERO</span>${realCommits.map((event) => marker(event, "real")).join("")}${zeroCommits.map((event) => marker(event, "zero")).join("")}<i class="cursor" style="left:${(state.real.events[state.index].observation_ms / finalMs) * 100}%"></i>`; $("#commit-counts").textContent = `REAL commits: ${realCommits.length} | ZERO commits: ${zeroCommits.length}`; const units = (commits) => commits.length ? commits.map((event, index) => `<div class="commit-unit ${index === commits.length - 1 ? "newest" : ""}"><span class="commit-meta">unit ${event.committed_unit_index + 1} | ${formatClock(event.observation_ms)} | ${event.decision_reason} | ${range(event)}</span>${escapeHtml(event.committed_target_text)}</div>`).join("") : "<p class=\"empty\">No committed unit yet.</p>"; $("#real-commits").innerHTML = units(realCommits); $("#zero-commits").innerHTML = units(zeroCommits); }
  function renderFeatures(real, zero) { const value = (event, name) => event.numeric_features ? event.numeric_features[name].toFixed(6).replace(/\.?(0+)$/, "") : "Not evaluated"; $("#features-content").innerHTML = `<table class="feature-table"><thead><tr><th>feature</th><th>REAL</th><th>ZERO</th></tr></thead><tbody>${FEATURES.map((name) => `<tr><td>${name}</td><td>${value(real, name)}</td><td>${value(zero, name)}</td></tr>`).join("")}</tbody></table>`; }
  function render() { const real = state.real.events[state.index]; const zero = state.zero.events[state.index]; $("#clock").textContent = formatClock(real.observation_ms); $("#event-meta").textContent = `event ${real.event_index} / ${state.real.events.length - 1} | source token ${real.source_token_end} / ${state.real.events.length - 1} | threshold ${real.threshold.toFixed(2)}`; renderSource(real, zero); $("#real-card").style.setProperty("--accent", "var(--real)"); $("#zero-card").style.setProperty("--accent", "var(--zero)"); $("#real-card").innerHTML = card("REAL", real); $("#zero-card").innerHTML = card("ZERO", zero); const divergence = real.decision !== zero.decision; const delta = real.p_commit == null || zero.p_commit == null ? "unavailable (WAIT was not evaluated)" : `${real.p_commit - zero.p_commit >= 0 ? "+" : ""}${(real.p_commit - zero.p_commit).toFixed(6)}`; $("#divergence-band").className = `divergence-band ${divergence ? "is-divergent" : ""}`; $("#divergence-band").innerHTML = divergence ? `<strong>POLICY DIVERGENCE</strong><span class="delta">Delta p = ${delta}</span><span>Prepared context changes policy timing at this observation.</span>` : "<strong>DECISIONS MATCH</strong>Both conditions share the same decision at this observation."; const sameSpan = isSameSpan(real, zero); $("#span-band").className = `span-band ${sameSpan ? "" : "is-cascade"}`; $("#span-band").innerHTML = sameSpan ? "<strong>SAME CANDIDATE SPAN</strong>Same incoming token, accumulated source, and candidate translation support a direct policy comparison." : "<strong>DIVERGED CANDIDATE BOUNDARIES</strong>Both policies hear the same incoming token, but earlier commit choices leave different amounts of source uncommitted. Later translations may differ because EnViT5 receives different source spans."; $("#first-divergence-note").hidden = state.index !== 131; renderTimeline(); if (!$("#features-content").hidden) renderFeatures(real, zero); }
  function stop() { if (state.timer) clearTimeout(state.timer); state.timer = null; $("#play").textContent = "Play"; }
  function schedule() { if (!state.timer) return; if (state.index >= state.real.events.length - 1) return stop(); const current = state.real.events[state.index]; const following = state.real.events[state.index + 1]; const delay = Math.min(MAX_PLAYBACK_DELAY_MS, Math.max(40, (following.observation_ms - current.observation_ms) / state.speed)); state.timer = setTimeout(() => { state.index += 1; render(); if (state.pauseOnDivergence && state.real.events[state.index].decision !== state.zero.events[state.index].decision) return stop(); schedule(); }, delay); }
  function jump(index) { stop(); state.index = Math.max(0, Math.min(index, state.real.events.length - 1)); render(); }
  function findDifference(direction) { for (let index = state.index + direction; index >= 0 && index < state.real.events.length; index += direction) if (state.real.events[index].decision !== state.zero.events[index].decision) return jump(index); }
  function interactiveTarget(target) { return target instanceof HTMLElement && (target.matches("input, select, textarea, button") || target.isContentEditable); }
  function setPauseOnDivergence(enabled) { state.pauseOnDivergence = enabled; $("#pause-on-divergence").checked = enabled; }
  function bind() { $("#reset").addEventListener("click", () => jump(0)); $("#next").addEventListener("click", () => jump(state.index + 1)); $("#previous").addEventListener("click", () => jump(state.index - 1)); $("#next-difference").addEventListener("click", () => findDifference(1)); $("#previous-difference").addEventListener("click", () => findDifference(-1)); $("#play").addEventListener("click", () => { if (state.timer) stop(); else { state.timer = -1; $("#play").textContent = "Pause"; schedule(); } }); $("#speed-controls").addEventListener("click", (event) => { const speed = event.target.dataset.speed; if (!speed) return; state.speed = Number(speed); document.querySelectorAll("[data-speed]").forEach((button) => button.classList.toggle("active", button === event.target)); }); $("#pause-on-divergence").addEventListener("change", (event) => setPauseOnDivergence(event.target.checked)); $("#bookmark").addEventListener("change", (event) => jump(Number(event.target.value))); $("#features-toggle").addEventListener("click", () => { const content = $("#features-content"); content.hidden = !content.hidden; $("#features-toggle").setAttribute("aria-expanded", String(!content.hidden)); $("#features-toggle").textContent = content.hidden ? "Show causal features" : "Hide causal features"; if (!content.hidden) renderFeatures(state.real.events[state.index], state.zero.events[state.index]); }); $("#presentation-toggle").addEventListener("click", () => { state.presentation = !state.presentation; document.body.classList.toggle("presentation-mode", state.presentation); $("#presentation-toggle").setAttribute("aria-pressed", String(state.presentation)); $("#presentation-toggle").textContent = state.presentation ? "Research mode" : "Presentation mode"; setPauseOnDivergence(state.presentation); }); document.addEventListener("keydown", (event) => { if (interactiveTarget(event.target) || event.altKey || event.ctrlKey || event.metaKey) return; const key = event.key.toLowerCase(); if ([" ", "arrowleft", "arrowright", "n", "p", "b", "r", "d"].includes(key)) event.preventDefault(); if (key === " ") $("#play").click(); if (key === "arrowleft") jump(state.index - 1); if (key === "arrowright") jump(state.index + 1); if (key === "n") findDifference(1); if (key === "p") findDifference(-1); if (key === "b") $("#bookmark").focus(); if (key === "r") jump(0); if (key === "d") setPauseOnDivergence(!state.pauseOnDivergence); }); }
  async function start() { try { const [real, zero, bookmarks] = await Promise.all([fetchJson(PATHS.real), fetchJson(PATHS.zero), fetchJson(PATHS.bookmarks)]); const initialIndex = validate(real, zero, bookmarks); state.real = real; state.zero = zero; state.bookmarks = bookmarks; $("#talk-meta").textContent = `Sims Witherspoon / AI Climate | ${real.talk_id} | P3 checkpoint ${real.checkpoint_sha256.slice(0, 12)}...`; $("#bookmark").innerHTML = `<option value="" selected disabled>Choose a bookmarked difference</option>${bookmarks.bookmarks.map((bookmark) => `<option value="${bookmark.event_index}">${escapeHtml(bookmark.label)} (${formatClock(bookmark.observation_ms, false)})</option>`).join("")}`; renderKnowledge(); bind(); $("#app").hidden = false; state.index = initialIndex; render(); } catch (error) { fail(error.message || String(error)); } }
  start();
})();
